### ISSUE TITLE
Is this maintained? What to do about Pypi?

### ISSUE THREAD

**Issue by frankier** [futurecolors/raven-harakiri#2]
It looks like some cleanups and extension have been attempted at https://github.com/LexMachinaInc/raven-harakiri . I have also been doing some improvements. Do you want to merge these in and update on Pypi or would it be easier to pass on maintainership (ideally including Pypi ownership) to me or LexMachinaInc?

Thanks for you work,
Frankie

**Comment by coagulant** [comment]
@frankier I'm not proud of the way raven-harakiri works. Never had enough time to implement logging harakiri properly, using uwsgi internals. Using alarm subsystem (https://github.com/unbit/uwsgi-sentry) seems much cleaner, but I have no direct solution.

I've given you a write permission for this repo. Need your pypi account to grant access here.
If people at LexMachinaInc also wish to join, just ask ;)
